---
development:
  cloud_name: dimg8ubwn
  api_key: '227454717272356'
  api_secret: osMQqxCvAakRxzen5CcXandHylw
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dimg8ubwn
  api_key: '227454717272356'
  api_secret: osMQqxCvAakRxzen5CcXandHylw
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dimg8ubwn
  api_key: '227454717272356'
  api_secret: osMQqxCvAakRxzen5CcXandHylw
  enhance_image_tag: true
  static_file_support: false
